fix: update cfg_aliases dependency to version 0.2.2
needed to fix semicolon_in_expressions_from_macros error in minver

```log
error: trailing semicolon in macro used in expression position
  --> build.rs:4:5
   |
 4 | /     cfg_aliases! {
 5 | |         android: { target_os = "android" },
 6 | |         dragonfly: { target_os = "dragonfly" },
 7 | |         ios: { target_os = "ios" },
...  |
27 | |         solarish: { any(illumos, solaris) },
28 | |     }
   | |_____^
   |
   = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
   = note: for more information, see issue #79813 <https://github.com/rust-lang/rust/issues/79813>
   = note: `#[deny(semicolon_in_expressions_from_macros)]` (part of `#[deny(future_incompatible)]`) on by default
   = note: this error originates in the macro `$crate::cfg_aliases` which comes from the expansion of the macro `cfg_aliases` (in Nightly builds, run with -Z macro-backtrace for more info)
   ```